### PR TITLE
Create ko.po

### PR DESCRIPTION
**Pull request by rlarjsdn122**

### CODE REVIEW

**Comment by prati0100** [comment]
Why did you close the PR? Anything wrong with it?

**Comment by rlarjsdn122** [comment]
@prati0100 

A Korean translation team already existed(https://github.com/git-l10n-ko/git-l10n-ko), so I closed this pull request. Is the translation team not related to Git GUI?

**Comment by prati0100** [comment]
No, I don't think that project is related to Git GUI. In fact, the git-gui project has been "abandoned" for some time now, and I only recently took over, so I don't really know who did the translations before.

Looking at the repo, it hasn't had a commit in over a year, so I'm not sure if the project is maintained anymore. I think it is a better idea to ask the git-l10n people if they're interested in maintaining translations for git-gui too.

**Comment by rlarjsdn122** [comment]
OK. I'll see. Thank you.

**Pull request closed without merging**
